-- Enable realtime for leaderboard updates
create publication if not exists supabase_realtime;
alter publication supabase_realtime add table public.leaderboard_totals;

-- Per-level completions
create table public.leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  level_id text not null,
  completed boolean default true,
  created_at timestamptz default now(),
  unique (user_id, level_id)
);

-- Aggregated scores for the live leaderboard
create table public.leaderboard_totals (
  user_id uuid primary key references auth.users on delete cascade,
  username text not null,
  xp int default 0 check (xp >= 0),
  completed int default 0 check (completed >= 0),
  updated_at timestamptz default now()
);

-- Row Level Security
alter table public.leaderboard enable row level security;
alter table public.leaderboard_totals enable row level security;

-- Anyone can read the leaderboard
create policy "Public read leaderboard rows" on public.leaderboard
  for select using (true);

create policy "Public read leaderboard totals" on public.leaderboard_totals
  for select using (true);

-- Users can only insert their own rows (service role key bypasses RLS for server-side writes)
create policy "Users insert own completion" on public.leaderboard
  for insert with check (auth.uid() = user_id);
