-- Idempotent fallback: run this if the leaderboard tables are missing

-- Per-level completions
create table if not exists public.leaderboard (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  level_id text not null,
  completed boolean default true,
  created_at timestamptz default now(),
  unique (user_id, level_id)
);

-- Aggregated scores for the live leaderboard
create table if not exists public.leaderboard_totals (
  user_id uuid primary key references auth.users on delete cascade,
  username text not null,
  xp int default 0 check (xp >= 0),
  completed int default 0 check (completed >= 0),
  updated_at timestamptz default now()
);

-- Row Level Security
alter table public.leaderboard enable row level security;
alter table public.leaderboard_totals enable row level security;

-- Policies (recreate if missing)
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'leaderboard' and policyname = 'Public read leaderboard rows'
  ) then
    create policy "Public read leaderboard rows" on public.leaderboard
      for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'leaderboard_totals' and policyname = 'Public read leaderboard totals'
  ) then
    create policy "Public read leaderboard totals" on public.leaderboard_totals
      for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'leaderboard' and policyname = 'Users insert own completion'
  ) then
    create policy "Users insert own completion" on public.leaderboard
      for insert with check (auth.uid() = user_id);
  end if;
end $$;

-- Enable realtime for leaderboard updates
do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;
end $$;

alter publication supabase_realtime add table public.leaderboard_totals;
