-- Feedback table for user messages
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  email text not null,
  message text not null,
  created_at timestamptz default now()
);

alter table public.feedback enable row level security;

-- Only the app can insert (service role); authenticated users can read their own
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'feedback' and policyname = 'Users read own feedback'
  ) then
    create policy "Users read own feedback" on public.feedback
      for select using (auth.uid() = user_id);
  end if;
end $$;
