-- Feedback table used by the /api/feedback route.
-- Inserts are performed via the service role key so RLS is optional.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete set null,
  email text,
  message text not null,
  created_at timestamptz default now()
);

-- Optional RLS: anonymous feedback is accepted, but the server uses the service role key.
alter table public.feedback enable row level security;

-- Allow anyone to insert feedback.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'feedback' and policyname = 'Public insert feedback'
  ) then
    create policy "Public insert feedback" on public.feedback
      for insert to public with check (true);
  end if;
end $$;
